# plugins:
#  - jekyll-redirect-from
#  - jekyll-github-metadata

# theme: jekyll-theme-slate
remote_theme: pmarsceill/just-the-docs

aux_links:
  "Jinja2C++ on GitHub":
    - "https://github.com/jinja2cpp/Jinja2Cpp"

title: "<img width='64' src='https://avatars0.githubusercontent.com/u/49841676?s=64&v=4'>Jinja2C++ project"
show_downloads: true
# github:
#  repository_url: https://github.com/flexferrum/Jinja2Cpp
#  zip_url: https://github.com/flexferrum/Jinja2Cpp/archive/0.9.1.zip
#  tar_url: https://github.com/flexferrum/Jinja2Cpp/archive/0.9.1.tar.gz
#  releases_url: https://github.com/flexferrum/Jinja2Cpp/releases
#  issues_url: https://github.com/flexferrum/Jinja2Cpp/issues
#  is_project_page: true
#  owner_url: https://github.com/flexferrum
#  owner_name: Flex Ferrum
#  project_tagline: Powerful text template engine for your C++ project!
  
