# plugins:
#  - jekyll-redirect-from
#  - jekyll-github-metadata

# theme: jekyll-theme-slate
remote_theme: pmarsceill/just-the-docs

title: Jinja2Cpp project
show_downloads: true
# github:
#  repository_url: https://github.com/flexferrum/Jinja2Cpp
#  zip_url: https://github.com/flexferrum/Jinja2Cpp/archive/0.9.1.zip
#  tar_url: https://github.com/flexferrum/Jinja2Cpp/archive/0.9.1.tar.gz
#  releases_url: https://github.com/flexferrum/Jinja2Cpp/releases
#  issues_url: https://github.com/flexferrum/Jinja2Cpp/issues
#  is_project_page: true
#  owner_url: https://github.com/flexferrum
#  owner_name: Flex Ferrum
#  project_tagline: Powerful text template engine for your C++ project!
  
